# Generated by Django 3.1.4 on 2021-02-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('demisto_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_title', models.TextField(blank=True, null=True)),
                ('ticket_created', models.DateTimeField(blank=True, null=True)),
                ('ticket_priority', models.IntegerField(blank=True, null=True)),
                ('ticket_priority2', models.IntegerField(blank=True, null=True)),
                ('ticket_status', models.TextField(blank=True, null=True)),
                ('ticket_owner', models.TextField(blank=True, null=True)),
                ('ticket_sourceip', models.TextField(blank=True, db_column='ticket_sourceIP', null=True)),
                ('ticket_details', models.TextField(blank=True, null=True)),
                ('ticket_vib_owner', models.TextField(blank=True, null=True)),
                ('ticket_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'internship',
                'managed': False,
            },
        ),
    ]
