# Generated by Django 3.1.4 on 2021-02-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('demisto_id', models.IntegerField()),
                ('comment_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comment',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='internship',
            options={'managed': False},
        ),
    ]
